### PR TITLE
Add Dijkstra's Algorithm (and add support for tests using pytest)

### PR DESCRIPTION
**Pull request by arushgupta2007**
Hi,

This pull request does 2 things:

1. Add Dijkstra's Algorithm
2. Change the File Structure to support tests using pytest.
    - The `search` and `sort` directories were moved to the `algorithms` directory
    - Created dummy files `main.py` and `algorithms/__init__.py`
    - Created `requirements.txt` for virtualenv support
    - Currently, I have only implemented tests for Dijkstra's Algorithm
    - To run the tests, from the root directory, run `pytest`

### CODE REVIEW

**Review by Ombucha — COMMENTED** [review]
Can you try using [`networkx`](https://pypi.org/p/networkx/), since that is what I am planning to use for other graph algorithms?
I am suggesting this because the aforementioned module:
- makes our life easier
- makes the code look cleaner
- allows beginners to understand the code easily

**Comment by arushgupta2007** [comment]
Hi,

I switched to using `networkx`. 

Also, `pytest` tests all files starting with `test`. So, I have renamed the `tests/graphs/shortest_path/dijkstra.py` to `tests/graphs/shortest_path/test_dijkstra.py`.

I have also seen python projects keeping their `tests` directory inside the package directory (for example: [numpy](https://github.com/numpy/numpy/tree/main/numpy/tests)), so I also moved `tests/` to `algorithms/`

Though there seems to be conflicting files `sort/insertion_sort.py` and `sort/merge_sort.py`. As I do not have write access, I cannot solve that :)

**Comment by Ombucha** [comment]
For some reason, I am not able to resolve the conflict directly. I have also tried using a CLI, but that leads to errors. Do you know of any way to fix this?

**Comment by arushgupta2007** [comment]
Hi,

As I do not know what issue you are facing, I do not know of a way to solve it. :)
I can point to some useful resources:
- [Coding Train on Youtube](https://youtu.be/JtIX3HJKwfo)
- [Github Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
- [Github Docs for CLI](https://docs.github.com/en/enterprise-server@3.1/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line)

**Comment by Ombucha** [comment]
Thank you!

**Comment by Ombucha** [comment]
Just a question; why have you added a [`main.py`](https://github.com/Pysics/Algorithms/blob/main/main.py/) file? It leads to [errors](https://github.com/Pysics/Algorithms/runs/5769591549?check_suite_focus=true) in Pylint.
I have deleted the file. I will add it back if it is important.

**Pull request merged**
